import { Metadata } from "next";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import RootLayoutClient from "./layout.client";
import "./globals.css";

export const metadata: Metadata = {
  title: "Pharmacy",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <RootLayoutClient session={session}>{children}</RootLayoutClient>
      </body>
    </html>
  );
}
