import { Metadata } from "next";
import RootLayoutClient from "./layout";

export const metadata: Metadata = {
  title: "Pharmacy",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <RootLayoutClient>{children}</RootLayoutClient>;
}
